# -*- coding: utf-8 -*-
"""Task_1_BDA (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKHMhj80JboBFo5tQhpMUV_Fnt_Z5Ok8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set_style('whitegrid')

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Load the Data"""

df = pd.read_csv("/content/drive/MyDrive/Python Programs/samplesuperstore - samplesuperstore.csv")
df.head()

"""## 2. Initial Data Understanding

Inspect structure, data types, and summary statistics before any cleaning.
"""

df.info()

df.describe(include='all').T

print("Shape of dataset:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

"""## 3. Data Cleaning

### 3.1 Check for missing values and duplicate rows
"""

print("Missing values per column:\n")
print(df.isnull().sum())

print("\nNumber of duplicate rows:", df.duplicated().sum())

"""### 3.2 Convert `Order Date` and `Ship Date` to datetime objects"""

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df[['Order Date', 'Ship Date']].dtypes

"""### 3.3 Clean text formatting across categorical attributes

Standardize `Category`, `Sub-Category`, and `Segment` by stripping extra whitespace
and applying consistent title-case formatting, so values like `" office supplies "`
and `"Office Supplies"` are treated the same.
"""

categorical_cols = ['Category', 'Sub-Category', 'Segment']

print("Unique values BEFORE cleaning:")
for col in categorical_cols:
    print(f"{col}: {sorted(df[col].unique())}")

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

print("Unique values AFTER cleaning:")
for col in categorical_cols:
    print(f"{col}: {sorted(df[col].unique())}")

"""### 3.4 Feature engineering — Delivery Days

Derive the number of days between order and shipment.
"""

df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df[['Order Date', 'Ship Date', 'Delivery Days']].head()

"""## 4. Summary Statistics for Numerical Attributes"""

numerical_cols = ['Sales', 'Quantity', 'Discount', 'Profit', 'Delivery Days']
df[numerical_cols].describe().T

print("Mean, Median, Std Dev for each numerical column:\n")
summary = pd.DataFrame({
    'Mean': df[numerical_cols].mean(),
    'Median': df[numerical_cols].median(),
    'Std Dev': df[numerical_cols].std(),
    'Min': df[numerical_cols].min(),
    'Max': df[numerical_cols].max()
})
summary

"""## 5. Exploratory Data Analysis

### 5.1 Total Sales by Category
"""

category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
print(category_sales)

category_sales.plot(kind='bar', figsize=(8, 5), color='steelblue')
plt.title("Sales by Category")
plt.ylabel("Total Sales")
plt.xlabel("Category")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""### 5.2 Sales Distribution"""

plt.figure(figsize=(8, 5))
sns.histplot(df['Sales'], bins=30, kde=True, color='teal')
plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""### 5.3 Total Sales by Sub-Category"""

subcat_sales = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
subcat_sales.plot(kind='barh', color='darkorange')
plt.title("Sales by Sub-Category")
plt.xlabel("Total Sales")
plt.ylabel("Sub-Category")
plt.tight_layout()
plt.show()

"""### 5.4 Sales by Customer Segment"""

segment_sales = df.groupby('Segment')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(6, 6))
plt.pie(segment_sales, labels=segment_sales.index, autopct='%1.1f%%', startangle=90)
plt.title("Sales Share by Segment")
plt.tight_layout()
plt.show()

"""### 5.5 Correlation Between Numerical Attributes"""

plt.figure(figsize=(6, 5))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()